#配置数据源
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/local_ship?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: root

      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      validation-query: select 1
      # 配置监控统计拦截的filters
#      filters: stat
      stat-view-servlet:
#        url-pattern: /druid/*
#        reset-enable: false
        reset-enable: false
        enabled: false

      web-stat-filter:
#        url-pattern: /*
#        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        enabled: false
      filter:
        config:
          enabled: false

  #配置 Jpa
  jpa:
    properties:
      hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
      ddl-auto: none
      show-sql: true
      format-sql: true
      use_sql_comments: true

  redis:
    #数据库索引
    database: 6
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间
    timeout: 5000
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

#jwt
jwt:
  header: Authorization
  access:
    token: access_token
  secret: mySecret
  # token 过期时间 8个小时
  expiration: 28800000
  auth:
    # 授权路径
    path: /login
    # 获取用户信息
    account: /info
    open-account: /user/simple-info

#是否开启 swagger-ui
swagger:
  enabled: true

remote:
  log:
    host: 172.16.169.239
    port: 22
    username: ytxt02
    password: sensortest028
    timeout: 600000
    path: /sensor/SHH
    folders: RG9H201026157B4492,RG9H201026157B44A0,RG9H210716157B4761,RG9H210716157B47A3,MG6Z210420157B4580
local:
  log:
    path: /Users/mrjavery/Desktop/ideaShip/wordSpace/logs/SH

apsat:
  setting:
    loginUrl: http://121.36.245.231:8080/api/v1/admin/user/login
    waterDeepUrl: http://121.36.245.231:8080/api/v1/public/queryinsertWaterDepth
    waterLineUrl: http://121.36.245.231:8080/api/v1/water/depth/queryDataByPoint
typhoon:
  token: 1c2d0fc97aaf0b98719e2a3197c694e7
tempPath: /root/excelTemp/

navigation:
  setting:
    # E航海用户登录地址
    loginUrl: http://enav.nhhb.org.cn/services/usermanage/v1/loginUser
    # 用户MRN
    userMrn: urn:mrn:china:appli-sys:YTWXSZSYS:v1.0:YTWXSZ
    # 用户名
    username: YTWXSZ
    # 用户密码
    password: SzYtWx@123
    # 系统终端授权key
    key: 05def4ecc5d6465ea22b98743daffda3
    # 3.3.	按区域获取航行警告/航行通告信息接口地址
    mSIbyAreaUrl: http://enav.nhhb.org.cn/services/MSI/v1/getMSIbyArea

weather:
  setting:
    # 获取气象信息接口地址
    weatherValueUrl: https://www.hifleet.com/hfWeatherApi/GetWeatherValue?&time=%s&f=036&lat=%s&lon=%s