package com.zkthinke.modules.apsat.ship.domain;

import lombok.Data;

import java.io.Serializable;

@Data
public class ShipPO implements Serializable {
    /**
     *
     *
     * @mbg.generated Sat Apr 03 12:32:58 CST 2021
     */
    private Long id;

    /**
     * 名称
     *
     * @mbg.generated Sat Apr 03 12:32:58 CST 2021
     */
    private String name;

    /**
     * MMSI编号
     *
     * @mbg.generated Sat Apr 03 12:32:58 CST 2021
     */
    private String mmsiNumber;

    /**
     * 呼号
     *
     * @mbg.generated Sat Apr 03 12:32:58 CST 2021
     */
    private String callSign;

    /**
     * IMO,唯一编号
     *
     * @mbg.generated Sat Apr 03 12:32:58 CST 2021
     */
    private String imoNumber;

    /**
     * 类型
     *
     * @mbg.generated Sat Apr 03 12:32:58 CST 2021
     */
    private String type;

    /**
     * 创建时间
     *
     * @mbg.generated Sat Apr 03 12:32:58 CST 2021
     */
    private Long createTime;

    /**
     * 更新时间
     *
     * @mbg.generated Sat Apr 03 12:32:58 CST 2021
     */
    private Long updateTime;

    /**
     * 最新航行信息 id
     *
     * @mbg.generated Sat Apr 03 12:32:58 CST 2021
     */
    private Long lastDetailId;

    /**
     *
     *
     * @mbg.generated Sat Apr 03 12:32:58 CST 2021
     */
    private String namePinyin;

    /**
     * 最新设备信息 id
     *
     * @mbg.generated Sat Apr 03 12:32:58 CST 2021
     */
    private Long lastDeviceId;

    /**
     * 最新设备同步时间
     *
     * @mbg.generated Sat Apr 03 12:32:58 CST 2021
     */
    private String lastDeviceStime;

    /**
     * 最新详情数据同步时间
     *
     * @mbg.generated Sat Apr 03 12:32:58 CST 2021
     */
    private String lastDetailStime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ship
     *
     * @mbg.generated Sat Apr 03 12:32:58 CST 2021
     */
    private static final long serialVersionUID = 1L;
}
