package com.zkthinke.modules.apsat.ship.domain;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * @TableName t_ship_detail
 */
@Data
public class ShipDetailHistoryPO implements Serializable {
    private String imoNumber;
    /**
     *
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Long id;

    /**
     * 船舶 id
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Long shipId;

    /**
     * 航行状态
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String sailingStatus;

    /**
     * 复位对地航程(当前航程)
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String resetVoyage;

    /**
     * 累计对地航程(累计航程)
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String totalVoyage;

    /**
     * 转向速度
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String steeringSpeed;

    /**
     * 对地航速
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String groundSpeed;

    /**
     * 当前经度
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String longitude;

    /**
     * 当前纬度
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String latitude;

    /**
     * 对地航向
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String cog;

    /**
     * 船首向
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String shipHead;

    /**
     * 出发时间
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Long departureTime;

    /**
     * 估计到达时间
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Long eta;

    /**
     * 目的地
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String destination;

    /**
     * 最大静态吃水
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String maxStaticDraft;

    /**
     * 风速
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String windSpeed;

    /**
     * 富裕水深
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String sensorDepth;

    /**
     * 相对风向
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String relativeWind;

    /**
     * 设备名称
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String deviceName;

    /**
     * 创建时间
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Long createTime;

    /**
     * 更新时间
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Long updateTime;

    /**
     * 数据采集时间
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Long collectTime;

    /**
     * 出发地
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String departure;

    /**
     * 同步数据 id
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Long sourceId;

    /**
     *
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String mmsiNumber;

    /**
     *
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String swsd;

    /**
     *
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String name;

    /**
     *
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String callSign;

    /**
     *
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_navigation_information
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Date dataSyncTime;
    private String rerativeWind;

    private String hdtHeading;
    private String rotTurnRate;
    private String zdaTimeZone;
    private String zdaTime;
    private String pstSpeed;
    private String pstTorque;
    private String pstThrust;
    private String pstPower;
    private static final long serialVersionUID = 1L;

    /**
     * TTM
     */
    private String typeofAcquistition;//获取类型
    private String timeofData;//UTC时间
    private String referenceTarget2;//参考目标
    private String targetStatus1;//目标状态
    private String targetName;//目标名称
    private String speedDidtanceunits;//速度/距离单位
    private String timetoCPA;//最小会遇时间
    private String distanceofClosest;//最小会遇距离
    private String targetCourseDegree;//目标航向，角度
    private String targetSpeed;//目标速度
    private String targetAzimuthAngle;//目标方位，角度
    private String targetDistacefromOwnShip;//目标与本船距离
    private String targetNumber;//目标号
    /**
     * OSD
     */
    private String speedUnits;//速度单位
    private String speedReference;//速度参考
    private String vesselSpeed;//船舶速度
    private String courseReference;//航向参考
    private String vesselCourse;//船舶航向
    private String headingStatus;//艏向状态
    private String heading;//艏向

    /**
     * RSA
     */
    private String starboardRudderSensor;//舵角
    private String starboardStatus;//状态
    /**
     * VBW
     */
    private String longitudinalWaterSpeed;//纵向对水速度
    private String transverseWaterSpeed;//横向对水速度
    private String longitudinalGroundSpeed;//纵向对地速度
    private String transverseGroundSpeed;//横向对地速度
    private String sternTransverseWaterSpeed;//船尾测得横向对水速度
    private String sternTransverseGroundSpeed;//船尾测得横向对地速度
    private String dataValidState;//对水速度状态

}