package com.zkthinke.modules.apsat.ship.detail.BO;

import lombok.Data;

import java.util.Date;

@Data
public class DetailVO {
    private String imoNumber;
    /**
     *
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Long id;

    /**
     * 船舶 id
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Long shipId;

    /**
     * 航行状态
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String sailingStatus;

    /**
     * 复位对地航程(当前航程)
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String resetVoyage;

    /**
     * 累计对地航程(累计航程)
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String totalVoyage;

    /**
     * 转向速度
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String steeringSpeed;

    /**
     * 对地航速
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String groundSpeed;

    /**
     * 当前经度
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String longitude;

    /**
     * 当前纬度
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String latitude;

    /**
     * 对地航向
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String cog;

    /**
     * 船首向
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String shipHead;

    /**
     * 出发时间
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Long departureTime;

    /**
     * 估计到达时间
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Long eta;

    /**
     * 目的地
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String destination;

    /**
     * 最大静态吃水
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String maxStaticDraft;

    /**
     * 风速
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String windSpeed;

    /**
     * 富裕水深
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String sensorDepth;

    /**
     * 相对风向
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String relativeWind;

    /**
     * 设备名称
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String deviceName;

    /**
     * 创建时间
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Long createTime;

    /**
     * 更新时间
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Long updateTime;

    /**
     * 数据采集时间
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Long collectTime;

    /**
     * 出发地
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String departure;

    /**
     * 同步数据 id
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Long sourceId;

    /**
     *
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String mmsiNumber;

    /**
     *
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String swsd;

    /**
     *
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String name;

    /**
     *
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String callSign;

    /**
     *
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_navigation_information
     *
     * @mbg.generated Tue Mar 30 15:46:51 CST 2021
     */
    private Date dataSyncTime;
    private String rerativeWind;

    private String hdtHeading;
    private String rotTurnRate;
    private String zdaTimeZone;
    private String zdaTime;
    private String pstSpeed;
    private String pstTorque;
    private String pstThrust;
    private String pstPower;
    private static final long serialVersionUID = 1L;


}
